opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - sorted_imports
  - toggle_bool

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - sorted_imports
  - function_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - file_length
  - large_tuple


excluded:
  - .build
  - .swiftpm
  - Tests

reporter: "xcode"
